"""First Migration

Revision ID: 2b9643ae6d37
Revises: 
Create Date: 2023-03-26 16:56:38.605300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9643ae6d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Original_url', sa.Text(), nullable=True),
    sa.Column('Shortened_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Websites')
    # ### end Alembic commands ###
